kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: app02
  namespace: app02
  labels:
    app: app02
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ocs-storagecluster-ceph-rbd
  volumeMode: Filesystem
