{{- if not $.Values.mcgstandalone.enabled }}
{{- if $.Values.rgw.enabled }}
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ocs-ceph-rgw
  annotations:
    description: Provides Object Bucket Claims (OBCs) using the RGW
    argocd.argoproj.io/sync-wave: "4"
provisioner: openshift-storage.ceph.rook.io/bucket
parameters:
  objectStoreName: ocs-cephobjectstore
  objectStoreNamespace: openshift-storage
  region: us-east-1
reclaimPolicy: Delete
volumeBindingMode: Immediate
{{- end }}
{{- end }}
