apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: app02-missing
  namespace: openshift-monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "95"
spec:
  groups:
    - name: app02-missing
      rules:
      - alert: App02NamespaceIsMissing
        expr: ((absent(kube_namespace_labels{namespace="app02"})) or (count( sum by (pod) (kube_pod_status_phase{phase=~"Pending|Unknown|Failed",namespace="app02"})) < 1))
        for: 1m
        labels:
          severity: critical
          snow_action: open_incident
          manifest: restore.yaml
          
        annotations:
          summary: "app02 is missing" #TODO Beautify these lines
          description: |
            app02 is missing. 
            
