{{- if not $.Values.mcgstandalone.enabled }}
{{- if $.Values.rgw.enabled }}
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: s3-rgw
  namespace: openshift-storage
  labels:
    app: rook-ceph-rgw
    ceph_daemon_id: ocs-cephobjectstore
    ceph_daemon_type: rgw
    rgw: ocs-cephobjectstore
    rook_cluster: openshift-storage
    rook_object_store: ocs-cephobjectstore
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  to:
    kind: Service
    name: rook-ceph-rgw-ocs-cephobjectstore
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Allow
  wildcardPolicy: None
{{- end }}
{{- end }}
