{{- if not $.Values.mcgstandalone.enabled }}
{{- if $.Values.cephtools.enabled }}
---
apiVersion: ocs.openshift.io/v1
kind: OCSInitialization
metadata:
  name: ocsinit
  namespace: openshift-storage
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  enableCephTools: true
{{- end }}
{{- end }}
