---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-environment
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/zaskan/ocp-event-driven
    # TODO: change branch
    targetRevision: deploy
    path: environment/resources/
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops
  syncPolicy: {}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: odf
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    targetRevision: 1.0.0
    repoURL: https://raw.githubusercontent.com/zaskan/ocp-event-driven/environment/charts/deploy
    chart: 10_odf
    helm:
      valueFiles: 
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-storage
  syncPolicy:
    syncOptions:
    - CreateNamespace=true

