apiVersion: v1
kind: Service
metadata:
  name: eda-routing
  namespace: aap
  annotations:
    argocd.argoproj.io/sync-wave: "40"
spec:
  selector:
    app: eda
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000