- name: Install Openshift Extras
  ansible.builtin.include_tasks: openshift_extras.yaml

- name: Add EDA credential
  ansible.controller.credential:
    name: "Event-Driven Ansible Credential"
    description: "Event-Driven Ansible Credential"
    organization: Default
    credential_type: "EDA"
    inputs:
      eda_host: "{{ hostvars['localhost']['eda_host'] }}"
      eda_user: "admin"
      eda_pass: "{{ hostvars['localhost']['eda_pass'] }}"

- name: Create APP02 job template
  ansible.controller.ob_template:
    name: "[JT] Create APP02 Event-Driven Ansible Objects"
    organization: "{{ default_organization | default('Default') }}"
    inventory: "Automation Controller Inventory"
    project: "OCP Event-Driven Demo Project"
    playbook: "playbooks/create_app02_repo.yaml"
    credentials:
      - "Gitea Credential"
      - "Event-Driven Ansible Credential"
      - "ServiceNow Credential"
      - "Red Hat Ansible Automation Platform Credential"
    ask_variables_on_launch: false
    allow_simultaneous: false
    execution_environment: "Default execution environment"
    state: present

- name: Create Servicenow EDA 
  ansible.controller.job_launch:
    job_template: "[JT] Create APP02 Event-Driven Ansible Objects"
  register: job

- name: Create APP02 job template
  ansible.controller.ob_template:
    name: "[JT] Create APP02 Event-Driven Ansible Objects"
    state: absent
  when: job.status == "successful"