credentials:
  - name: "Red Hat Ansible Automation Platform Credential"
    desc: "Red Hat Ansible Automation Platform Credential"
    org: "{{ default_organization | default('Default') }}"
    type: "Red Hat Ansible Automation Platform"
    inputs:
      host: "{{ hostvars['localhost']['aap_host'] }}"
      username: "admin"
      password: "{{ hostvars['localhost']['aap_pass'] }}"
  - name: "ServiceNow Credential"
    desc: "ServiceNow Credential"
    org: Default
    type: "ServiceNow"
    inputs:
      sn_host: "{{ snow_instance_host }}"
      sn_username: "{{ snow_instance_username }}"
      sn_password: "{{ snow_instance_password }}"
  - name: "Event-Driven Ansible Credential"
    desc: "Event-Driven Ansible Credential"
    org: Default
    type: "EDA"
    inputs:
      eda_host: "{{ eda_host }}"
      eda_user: "{{ eda_user }}"
      eda_pass: "{{ eda_pass }}"
  - name: "Gitea Credential"
    desc: "Gitea Credential"
    org: Default
    type: "Gitea"
    inputs:
      gitea_repo: "http://gitea.gitea.svc.cluster.local:3000/gitea/{{ gitea_repo }}.git"
      gitea_email: "{{ gitea_email }}"
      gitea_username: "{{ gitea_username }}"
      gitea_password: "{{ gitea_password }}"
  - name: "Openshift Credential"
    desc: "Openshift Credential"
    org: Default
    type: "OpenShift or Kubernetes API Bearer Token"
    inputs:
      host: "{{ openshift_host }}"
      bearer_token: "{{ openshift_token }}"
