credentials:
  - name: "Red Hat Ansible Automation Platform Credential"
    desc: "Red Hat Ansible Automation Platform Credential"
    org: "{{ default_organization | default('Default') }}"
    type: "Red Hat Ansible Automation Platform"
    inputs:
      host: "{{ hostvars['localhost']['aap_host'] }}"
      username: "admin"
      password: "{{ hostvars['localhost']['aap_pass'] }}"
