credentials:
  - name: "Red Hat Ansible Automation Platform Credential"
    desc: "Red Hat Ansible Automation Platform Credential"
    org: "{{ default_organization | default('Default') }}"
    type: "Red Hat Ansible Automation Platform"
    inputs:
      host: "{{ aap_host }}"
      username: "{{ aap_user }}"
      password: "{{ aap_pass }}"