jobtemplates:
  - name: "[JT] Open Servicenow Incident"
    org: "{{ default_organization | default('Default') }}"
    inv: "Automation Controller Inventory"
    project: "OCP Event-Driven Demo Project"
    playbook: "playbooks/alertmanager_open_snow_incident.yaml"
    creds:
      - "ServiceNow Credential"
    ask_variables_on_launch: true
    allow_simultaneous: false
    execution_environment: "Default execution environment"

  - name: "[JT] Close Servicenow Incident"
    org: "{{ default_organization | default('Default') }}"
    inv: "Automation Controller Inventory"
    project: "OCP Event-Driven Demo Project"
    playbook: "playbooks/ansible_close_snow_incident.yaml"
    creds:
      - "ServiceNow Credential"
    ask_variables_on_launch: true
    allow_simultaneous: false
    execution_environment: "Default execution environment"

  - name: "[JT] Extend Physical Volume"
    org: "{{ default_organization | default('Default') }}"
    inv: "Automation Controller Inventory"
    project: "OCP Event-Driven Demo Project"
    playbook: "playbooks/extend_pvc.yaml"
    creds:
      - "Gitea Credential"
    ask_variables_on_launch: true
    allow_simultaneous: false
    execution_environment: "Default execution environment"


