projects:
  - name: "OCP Event-Driven Demo Project"
    desc: "OCP Event-Driven Demo Project"
    org: "{{ default_organization | default('Default') }}"
    git_url: "https://github.com/zaskan/ocp-event-driven.git"
    git_branch: "main"
    update_on_launch: false
