workflowjobtemplates:
  - name: "[WF] Extend Openshift Physical Volume"
    org: "{{ default_organization | default('Default') }}"
    inv: ""
    ask_variables_on_launch: true
    ask_limit_on_launch: false
    allow_simultaneous: true
    steps:
       - identifier: Extend Physical Volume
         unified_job_template:
           organization:
             name: "{{ default_organization | default('Default') }}"
           name: "[JT] Extend Physical Volume"
           type: job_template
         credentials: []
         related:
           success_nodes:
             - identifier: "Close Servicenow Ticket"
           failure_nodes: []
           always_nodes: []
           credentials: []
       - identifier: Close Servicenow Ticket
         unified_job_template:
           organization:
             name: "{{ default_organization | default('Default') }}"
           name: "[JT] Servicenow Actions"
           type: job_template
         credentials: []
         related:
           success_nodes: []
           failure_nodes: []
           always_nodes: []
           credentials: []
