workflowjobtemplates:
  - name: "[WF] Extend Openshift Physical Volume"
    org: "{{ default_organization | default('Default') }}"
    inv: ""
    ask_variables_on_launch: true
    ask_limit_on_launch: false
    allow_simultaneous: true
    steps:
       - identifier: Set Alert Acknowledge
         unified_job_template:
           organization:
             name: "{{ default_organization | default('Default') }}"
           name: "[JT] Set Alert to Acknowledge"
           type: job_template
         credentials: []
         related:
           success_nodes:
             - identifier: "Extend Physical Volume"
           failure_nodes: []
           always_nodes: []
           credentials: []
       - identifier: Extend Physical Volume
         unified_job_template:
           organization:
             name: "{{ default_organization | default('Default') }}"
           name: "[JT] Extend Physical Volume"
           type: job_template
         credentials: []
         related:
           success_nodes:
             - identifier: "Synchronize ArgoCD"
           failure_nodes: []
           always_nodes: []
           credentials: []
       - identifier: Synchronize ArgoCD
         unified_job_template:
           organization:
             name: "{{ default_organization | default('Default') }}"
           name: "[JT] Synchronize ArgoCD"
           type: job_template
         credentials: []
         related:
           success_nodes:
             - identifier: "Close Servicenow Ticket"
           failure_nodes: []
           always_nodes: []
           credentials: []
       - identifier: Close Servicenow Ticket
         unified_job_template:
           organization:
             name: "{{ default_organization | default('Default') }}"
           name: "[JT] Close Servicenow Incident"
           type: job_template
         credentials: []
         related:
           success_nodes: []
           failure_nodes: []
           always_nodes: []
           credentials: []

  - name: "[WF] Restore Application"
    org: "{{ default_organization | default('Default') }}"
    inv: ""
    ask_variables_on_launch: true
    ask_limit_on_launch: false
    allow_simultaneous: true
    steps:
       - identifier: Set Alert Acknowledge
         unified_job_template:
           organization:
             name: "{{ default_organization | default('Default') }}"
           name: "[JT] Set Alert to Acknowledge"
           type: job_template
         credentials: []
         related:
           success_nodes:
             - identifier: "Restore Application"
           failure_nodes: []
           always_nodes: []
           credentials: []
       - identifier: Restore Application
         unified_job_template:
           organization:
             name: "{{ default_organization | default('Default') }}"
           name: "[JT] Restore Application"
           type: job_template
         credentials: []
         related:
           success_nodes:
             - identifier: "Close Servicenow Ticket"
           failure_nodes: []
           always_nodes: []
           credentials: []
       - identifier: Close Servicenow Ticket
         unified_job_template:
           organization:
             name: "{{ default_organization | default('Default') }}"
           name: "[JT] Close Servicenow Incident"
           type: job_template
         credentials: []
         related:
           success_nodes: []
           failure_nodes: []
           always_nodes: []
           credentials: []