---
- name: Test Snow API
  hosts: localhost
  tasks:

    - name: Update incident INC0010004
      servicenow.itsm.incident_info:
        instance:
          host: https://dev243054.service-now.com
          username: admin
          password: si-6A2CJ%psK
        number: "INC0010004"
      register: result

    - debug: msg="{{ result.records[0].sys_id }}"

    - name: Closed incident
      servicenow.itsm.incident:
        instance:
          host: https://dev243054.service-now.com
          username: admin
          password: si-6A2CJ%psK
        resource: sc_incident
        action: patch
        sys_id: "{{ result.records[0].sys_id }}"
        data:
          state: 3
          incident_state: 7
          number: "INC0010004"
          close_code: "Resolved by Caller"
          close_notes: "Incident fixed by EVent-Driven Ansible."
          caller: "eda"
