- name: Close incident {{ servicenow_incident_number }}
  servicenow.itsm.incident:
    state: resolved
    number: "{{ servicenow_incident_number }}"
    close_code: "Solved (Permanently)"
    close_notes: "Incident fixed by EVent-Driven Ansible. {{ servicenow_incident_notes }}"
    caller: "{{ servicenow_incident_caller }}"
