---
- name: Open ServiceNow incident
  ansible.builtin.include_tasks:
    file: open_incident.yaml
    apply:
      vars:
        servicenow_action: "{{ servicenow_action }}"
        servicenow_incident_title: "{{ servicenow_incident_title }}"
        servicenow_incident_description: "{{ servicenow_incident_description }}"
