---
- name: Install Demo in OpenShift
  gather_facts: false
  hosts: localhost

  vars_files:
    - vars.yaml

  tasks:
    - name: Create Demo namespaces
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: project.openshift.io/v1
          kind: Project
          metadata:
            name: "{{ namespace.name }}"
      loop: "{{ demoNamespaces }}"
      loop_control:
        loop_var: namespace

    - name: Install Operators
      ansible.builtin.include_role:
        name: install_operators

    - name: ArgoCD
      ansible.builtin.include_role:
        name: argo_cd

    - name: Create demo environment on ArgoCD
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            name: ocp-event-driven-environment
            namespace: openshift-gitops
            finalizers:
              - resources-finalizer.argocd.argoproj.io
          spec:
            project: default
            source:
              repoURL: https://github.com/zaskan/ocp-event-driven.git
              targetRevision: main
              path: environment/resources/
              directory:
                recurse: true
            destination:
              server: https://kubernetes.default.svc
              namespace: openshift-gitops
            syncPolicy:
              automated:
                prune: true
                selfHeal: true

    - name: Servicenow
      ansible.builtin.include_role:
        name: servicenow_casc
      vars:
        snow_eda_username: "{{ snow_eda_username }}"
        snow_eda_password: "{{ snow_eda_password }}"

    - name: Ansible Controller
      ansible.builtin.include_role:
        name: controller_casc

    - name: Ansible EDA
      ansible.builtin.include_role:
        name: eda_casc
      vars:
        eda_casc_controller_token: "{{ application_token }}"

    - name: Extras
      ansible.builtin.include_role:
        name: extras

    - name: Display message after role execution
      ansible.builtin.debug:
        msg: "Running tasks after role execution"
