---
- name: Uninstall Demo
  hosts: localhost
  tasks:

    - name: Remove demo environment on ArgoCD
      kubernetes.core.k8s:
        state: absent
        api_version: argoproj.io/v1alpha1
        kind: Application
        namespace: openshift-gitops
        name: ocp-event-driven-environment

    - name: Delete Demo namespaces
      kubernetes.core.k8s:
        state: absent
        definition:
          apiVersion: project.openshift.io/v1
          kind: Project
          metadata:
            name: "{{ namespace.name }}"
      loop: "{{ demoNamespaces }}"
      loop_control:
        loop_var: namespace

    - name: Delete Extras
      kubernetes.core.k8s:
        state: absent
        src: "{{ item }}"
      with_fileglob:
        - "roles/post_tasks/files/alertmanager/*"
        - "roles/post_tasks/files/app02/namespace/*"
        - "roles/post_tasks/files/app02/others/*"
  vars_files:
    - vars.yaml
