decision_environments:
  - name: Default Decision Environment
    description: Default Decision Environment
    image_url: "registry.redhat.io/ansible-automation-platform-24/de-supported-rhel8:1.0.5-24"
    credential: registry_credential

  - name: Servicenow Decision Environment
    description: Servicenow Decision Environment
    image_url: "quay.io/ansible_eda/ansible-eda-de:1.1"