kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: app01
  labels:
    app: app01
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ocs-storagecluster-ceph-rbd
  volumeMode: Filesystem
