---
- name: Watch for new snow records and alerts
  hosts: localhost
  sources:
    - ansible_ssa.eda.alertmanager:
        host: 0.0.0.0
        port: 5000
        data_host_path: ""
  rules:
    - name: Trigger Request - New ServiceNow User
      condition: event.short_description contains "usage"
      action:
        debug:
          msg: Simple debug message
