---
- name: Watch for PVCUsageHigh
  hosts: localhost
  sources:
    - ansible.eda.alertmanager:
        host: 0.0.0.0
        port: 5000
        data_host_path: ""
  rules:
    - name: Get PVCUsageHigh alerts
      condition: event.alert.labels.alertname == "PVCUsageHigh"
      action:
        run_job_template:
          name: "[JT] Servicenow Actions"
          organization: "Default"
          job_args:
            extra_vars:
              payload: "{{ event.alert }}"