---
- name: Watch for PVCUsageHigh
  hosts: localhost
  sources:
    - ansible.eda.alertmanager:
        host: 0.0.0.0
        port: 5000
        data_host_path: ""
  rules:
    - name: Get PVCUsageHigh alerts
      condition: event is defined
      action:
        run_job_template:
          name: Demo Job Template
          organization: Default
