---
- name: EDA Listener for Alertmanager and Servicenow
  hosts: localhost
  sources:
    - name: Listen to Alertmanager
      ansible.eda.alertmanager:
        host: 0.0.0.0
        port: 5000
        data_host_path: ""

    - name: Check new Incidents
      cloin.eda.snow_records:
        instance: "{{ instance }}"
        username: "{{ username }}"
        password: "{{ password }}"
        table: incident
        interval: 1
  rules:
    - name: Get Alertmanager Alerts
      condition: event.alert.labels.alertname == "PVCUsageHigh" or event.alert.labels.alertname == "App02NamespaceIsMissing"
      action:
        run_job_template:
          name: "[JT] Open Servicenow Incident"
          organization: "Event-Driven Ansible"
          job_args:
            extra_vars:
              payload: "{{ event.alert }}"

    - name: Trigger Remediation for PVCUsageHigh
      condition: event.short_description == "PVCUsageHigh"
      action:
        run_workflow_template:
          name: "[WF] Extend Openshift Physical Volume"
          organization: "Event-Driven Ansible"
          job_args:
            extra_vars:
              incident_id: "{{ event.number }}"
              description: "{{ event.description }}"

    - name: Trigger Remediation for App02NamespaceIsMissing
      condition: event.short_description == "App02NamespaceIsMissing"
      action:
        run_workflow_template:
          name: "[WF] Restore Application"
          organization: "Event-Driven Ansible"
          job_args:
            extra_vars:
              incident_id: "{{ event.number }}"
              description: "{{ event.description }}"
              app_name: "app02"
