kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: app02
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: ocs-storagecluster-cephfs
  volumeMode: Filesystem
