---
- name: Pass parameters from Alertmanager to Servicenow
  hosts: localhost
  gather_facts: false

  tasks:

    - name: Perform a Servicenow API Call
      ansible.builtin.include_role:
        name: servicenow
      vars:
        servicenow_action: "{{ payload.labels.snow_action }}"
        servicenow_incident_title: "{{ payload.labels.alertname }}"
        servicenow_incident_description: "{{ payload.annotations.description }}{{ payload.annotations.summary }}"
        servicenow_incident_caller: "alertmanager"
        servicenow_incident_impact: "low"
        servicenow_incident_urgency: "high"