---
- name: Pass parameters from Alertmanager to Servicenow
  hosts: localhost
  gather_facts: false

  tasks:
    - debug: msg="{{ payload }}"
#    - name: Perform a Servicenow API Call
#      ansible.builtin.include_role:
#        name: servicenow
#      vars:
#        parameters: "{{ snow_action }}"
