---
- name: Backup / Restore Operations
  hosts: localhost
  gather_facts: true

  tasks:

    - name: Execute Operation
      ansible.builtin.include_role:
        name: backup
      vars:
        app_name: "{{ app_name }}"
        operation: "{{ operation }}"
        git_operation: clone
      register: backup_result

