---
- name: Create app02 repository and upload rulebook
  hosts: localhost
  gather_facts: true
  tasks:

    - name: Create app02 repository
      ansible.builtin.uri:
        url: "{{ lookup('env','GITEA_REPO') | urlsplit('scheme')}}://{{ lookup('env','GITEA_REPO') | urlsplit('hostname') }}:{{ lookup('env','GITEA_REPO') | urlsplit('port') }}/api/v1/user/repos"
        force_basic_auth: true
        user: "{{ lookup('env','GITEA_USERNAME') }}"
        password: "{{ lookup('env','GITEA_PASSWORD') }}"
        method: POST
        headers:
          Content-Type: application/json
        body_format: "json"
        body:
          auto_init: true
          default_branch: "master"
          name: "app02"
          private: false
          trust_model: "default"
        status_code:
          - 201
          - 409

    - name: Create a temp directory for app02
      ansible.builtin.file:
        path: /tmp/app02
        state: directory
        mode: '0755'

    - name: Clone Configuration Repository
      ansible.builtin.include_role:
        name: git
      vars:
        git_repository: "{{ lookup('env', 'GITEA_REPO') }}"
        git_directory: "/tmp/app02"
        git_operation: clone
      register: git_result

    - name: Clone app02 repository
      ansible.builtin.git:
        repo: "{{ lookup('env', 'GITEA_REPO') | urlsplit('scheme') }}://{{ lookup('env', 'GITEA_REPO') | urlsplit('hostname') }}:{{ lookup('env', 'GITEA_REPO') | urlsplit('port') }}/gitea/app02.git"
        dest: /tmp/app02
        clone: true
        update: true
        force: true

    - name: Create Rulebooks directory
      ansible.builtin.file:
        path: /tmp/app02/rulebooks
        state: directory
        mode: '0755'

    - name: Template Servicenow Rulebook
      ansible.builtin.template:
        src: ../templates/snow-rulebook.yaml.j2
        dest: /tmp/app02/rulebooks/snow-rulebook.yaml
        mode: '0644'

    - name: Commit configuration to repository
      ansible.builtin.include_role:
        name: git
      vars:
        git_operation: push
        git_repository: "{{ lookup('env', 'GITEA_REPO') | urlsplit('scheme') }}://{{ lookup('env', 'GITEA_REPO') | urlsplit('hostname') }}:{{ lookup('env', 'GITEA_REPO') | urlsplit('port') }}/gitea/app02.git"
        git_directory: "/tmp/app02"
        git_email: "{{ lookup('env','GITEA_EMAIL') }}"
        git_user: "{{ lookup('env','GITEA_USERNAME') }}"
        git_message: "Added Rulebook"
      register: git_result