---
- name: Modify Openshift Object
  hosts: localhost
  gather_facts: true

  tasks:

    - name: Get current date
      ansible.builtin.set_fact:
        operation_time: "{{ ansible_date_time.iso8601_basic_short }}"

    - name: Clone Configuration Repository
      ansible.builtin.include_role:
        name: git
      vars:
        git_repository: "{{ git_repository }}"
        git_directory: "/tmp/{{ operation_time }}"
        git_operation: clone
      register: git_result

    - name: Get Project Name
      ansible.builtin.find:
        paths:
          - "/tmp/{{ operation_time }}"
        file_type: file
        recurse: false
        use_regex: true
        patterns:
          - '^[/\w]*'
      register: project_directory


    - debug: msg="{{ project_directory }}"