---
- name: Silence Alertmanager Alarm
  hosts: localhost
  gather_facts: False
  tasks:
    - name: Silence Alarms
      kubernetes.core.k8s_exec:
        namespace: openshift-monitoring
        pod: alertmanager-main-0
        command: "amtool silence add --alertmanager.url http://localhost:9093  alertname={{ ansible_eda.event.short_description }} --comment 'ACK'"

# Added the two tasks below in order to stop alertmanager sending alerts. TODO: Check alertmanager configuration to avoid sending alerts once we ACK the first one.

    - name: Disable
      kubernetes.core.k8s:
        state: absent
        api_version: monitoring.coreos.com/v1
        kind: PrometheusRule
        namespace: app01
        name: app01-pvc

    - name: Disable
      kubernetes.core.k8s:
        state: absent
        api_version: monitoring.coreos.com/v1beta1
        kind: AlertmanagerConfig
        namespace: app01
        name: eda-routing

