apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app02
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  destination:
    namespace: app02
    server: 'https://kubernetes.default.svc'
  source:
    path: .
    repoURL: 'http://gitea.gitea.svc.cluster.local:3000/gitea/app02'
    targetRevision: master
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true